# Generated by Django 4.0.3 on 2022-04-11 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_message_seen_message_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
