# Generated by Django 4.0.3 on 2022-04-18 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
