# Generated by Django 4.0.3 on 2022-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_friend_requests_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(default='backgrounds/default.jpg', upload_to='backgrounds'),
        ),
    ]
