# Generated by Django 4.0.4 on 2022-05-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaton_from',
            new_name='notificaiton_from',
        ),
    ]
