# Generated by Django 4.0.4 on 2022-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_notificaton_from_notification_notificaiton_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.friendrequest'),
        ),
    ]
