# Generated by Django 4.0.4 on 2022-05-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_friend_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaiton_from',
            new_name='notification_from',
        ),
    ]
